In [280]:
import requests
from pprint import pprint
import pandas as pd
import re
import numpy as np

In [8]:
#test
base_url = "https://api-v3.igdb.com/"
header={"user-key":"12e42347a0a2ee0b7a738578e40fe301 "}
end_point='games'
params={"fields":"aggregated_rating,name,videos,game_modes,genres", "filter[aggregated_rating][gt]":"0", "limit":"100",}
# filter[platform][eq]=48

In [225]:
#primary ds
base_url = "https://api-v3.igdb.com/games"
header={"user-key":"12e42347a0a2ee0b7a738578e40fe301"}
params={"fields": "age_ratings,aggregated_rating,aggregated_rating_count,category,dlcs,expansions,first_release_date,follows,franchise,franchises,game_modes,hypes,keywords, multiplayer_modes,name,popularity,pulse_count,rating,rating_count,release_dates, similar_games,slug,storyline,summary,tags,themes,time_to_beat,total_rating,total_rating_count,artworks,url,genres", "order":"popularity:desc", "limit" :"500"}

In [147]:
# game modes
base_url = "https://api-v3.igdb.com/game_modes"
header={"user-key":"12e42347a0a2ee0b7a738578e40fe301"}
params={"fields":"name,slug, url ", "limit" : 500 }

In [142]:
#genres
base_url = "https://api-v3.igdb.com/genres"
header={"user-key":"12e42347a0a2ee0b7a738578e40fe301"}
params={"fields":"slug, url ", "limit" : 500 }

In [151]:
#themes
base_url = "https://api-v3.igdb.com/themes"
header={"user-key":"12e42347a0a2ee0b7a738578e40fe301"}
params={"fields":"slug, url ", "limit" : 500 }

In [212]:
#Age Rating Descriptions
base_url = "https://api-v3.igdb.com/age_rating_content_descriptions"
header={"user-key":"12e42347a0a2ee0b7a738578e40fe301"}
params={"fields":"*", "limit" : 500 }

In [361]:
#Age Ratings
ids = []
ratings = []
for item in rates:
    base_url = "https://api-v3.igdb.com/age_ratings"
    header={"user-key":"12e42347a0a2ee0b7a738578e40fe301"}
    params={"fields":"*", "limit" : 500, "filter[id][eq]": item }
    response = requests.get(base_url,headers=header,params=params)
    print(response)
    df = pd.DataFrame(response.json())
    ids.append(df['id'][0])
    ratings.append(df['rating'][0])
    
#/release_dates/?fields=*&filter[platform][eq]=48&order=date:asc&filter[date][gt]=1500619813000&expand=game

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [369]:
#df = df.set_index('id')
#df = df.drop("category", axis=1)
df = pd.DataFrame(list(zip(ids, ratings)), 
               columns =['ids', 'ratings']) 
df.set_index('ids')
df.to_csv('ids_&_ratingCode_ds.csv')

In [ ]:
df = df.set_index('id')

In [226]:
response = requests.get(base_url,headers=header,params=params)
print(response)
df = pd.DataFrame(response.json())
df.columns

<Response [200]>

Index(['age_ratings', 'aggregated_rating', 'aggregated_rating_count',
       'artworks', 'category', 'dlcs', 'expansions', 'first_release_date',
       'franchise', 'franchises', 'game_modes', 'genres', 'hypes', 'id',
       'keywords', 'multiplayer_modes', 'name', 'popularity', 'pulse_count',
       'rating', 'rating_count', 'release_dates', 'similar_games', 'slug',
       'storyline', 'summary', 'tags', 'themes', 'time_to_beat',
       'total_rating', 'total_rating_count', 'url'],
      dtype='object')

In [240]:
df = df.drop(['age_ratings', 'artworks', 'dlcs', 'expansions', 'franchises', 'game_modes', 'genres',\
          'keywords', 'multiplayer_modes', 'release_dates', 'similar_games', 'tags', 'themes'], axis=1)

In [261]:
#This is only necessary for cleaning if reading from csv. From Json ignore this step
age_ratings_set = set()

for i in age_ratings:
    i = i.replace('[', "")
    i = i.replace(' ', "")
    i = i.replace('0', "")
    i = i.replace(']', "").split(",")
    age_ratings_set.update(i)

age_ratings_set = list(new_set)

AttributeError: 'list' object has no attribute 'replace'

In [275]:
age_ratings = tbo_df[['age_ratings', 'id']]
age_ratings = age_ratings.dropna()
age_ratings

        age_ratings      id
0           [25494]  115278
1           [25488]  120268
2           [25485]  105049
3           [25457]  113344
4    [25428, 25841]   19164
5            [6032]    1877
6           [24208]  115653
8    [25528, 25529]   96217
10          [24721]   26845
11          [25495]   55038
13           [9372]   22472
14          [23490]   22490
17          [25530]   55190
18   [25533, 25534]  114286
20   [25535, 25536]   26145
24   [25267, 25437]   27092
30          [22565]   56033
31          [23950]   55199
35           [8367]   18623
39   [20787, 20788]   67166
40          [23541]   28168
41          [22609]   28309
44   [23476, 23477]   24426
49   [25537, 25538]    3772
50   [25539, 25540]   18225
52   [26266, 26348]   19564
55          [14040]   55036
58   [23157, 23158]   28070
59   [24233, 24234]  115737
60          [13999]   25646
..              ...     ...
448   [1110, 19910]     832
453  [14065, 14066]     359
455    [6453, 6454]    2918
456  [10960, 20842]   11162
457           [419]     241
459  [21038, 21039]    4843
460   [6468, 24580]    7334
461         [25570]   17446
463          [4163]    7213
464    [8461, 8462]    5589
466  [11346, 11347]   21642
469  [14240, 21379]   28540
471         [12621]   36732
472         [12376]   28472
474     [96, 12190]    1011
475         [25259]  119305
479  [13899, 13900]   22439
480  [25571, 25572]    7843
481  [11621, 11622]    5503
482  [13075, 13076]   11233
483         [26114]   74701
485  [23069, 23070]   16287
486   [9162, 11319]    7323
487    [828, 11281]     233
490  [23806, 24266]   19686
491         [22048]   16999
492         [24883]  115284
496   [6376, 23114]     587
497  [12499, 12500]   11550
498  [25573, 25574]  101211

[267 rows x 2 columns]

In [284]:
#This takes a lists out of dfs into new records. r = result
#Age ratings
lst_col = 'age_ratings'
r = pd.DataFrame({
      col:np.repeat(age_ratings[col].values, age_ratings[lst_col].str.len())
      for col in age_ratings.columns.drop(lst_col)}
    ).assign(**{lst_col:np.concatenate(age_ratings[lst_col].values)})[age_ratings.columns]

In [294]:
#Removing all newlines, all commas
clean_df = clean_df.replace(r'\\n',' ', regex=True) 
clean_df = clean_df.replace(r',',';', regex=True)

In [299]:
clean_df.to_csv("primary_ds_new.csv")

In [350]:
r = r.set_index('id')

In [359]:
rates = r.loc[:,'age_ratings']

In [360]:
for rate in rates:
    print(rate)

25494
25488
25485
25457
25428
25841
6032
24208
25528
25529
24721
25495
9372
23490
25530
25533
25534
25535
25536
25267
25437
22565
23950
8367
20787
20788
23541
22609
23476
23477
25537
25538
25539
25540
26266
26348
14040
23157
23158
24233
24234
13999
23715
22851
22852
12700
23160
23161
25541
25542
20018
20019
24445
24853
9776
11875
15813
10718
10719
15371
990
12749
22680
25543
26213
7825
7826
23335
25545
21049
21050
23119
21036
21037
4033
24871
23542
6304
7633
25546
25547
26209
26210
6358
11487
15035
9369
24717
21056
24268
25548
25549
25187
23126
4422
12789
6280
6281
23943
12208
9370
26292
26293
12043
12044
25550
25551
23747
23748
21775
7579
15986
23550
26094
8637
8638
8639
25260
6477
25967
25552
25553
33
18508
18509
13785
24898
9068
14051
23949
10942
12352
15380
23050
23556
23557
25426
6227
25284
25554
25555
59
12197
13157
21310
23539
23980
8753
6073
12751
24577
12046
13894
4687
6082
10850
16076
23140
23008
23737
22322
6643
11242
22054
13142
11962
11963
8470
12393
23051
23052
21679
15013
9135
23091
23975
16199
16200
15659
15660
4804
11143
24229
24230
22377
25556
12552
12553
11219
25176
11042
23999
10876
10877
6189
25557
25558
24102
22563
12803
12804
18980
12550
12551
24872
24147
24209
24062
9371
12678
12679
11580
8772
8773
3891
11129
24668
15352
15353
14939
19486
12720
12721
23692
23693
25490
25491
25559
25560
6055
6056
11298
11299
24567
21047
21048
7004
7005
7061
24447
6563
7907
20025
1444
5369
24762
24763
23929
26026
22214
15329
19580
4990
11069
14135
14136
1222
13032
22498
22499
11260
11261
9481
9482
23580
11842
11843
9534
24099
12663
8886
22352
19878
25169
1342
21348
7186
10634
12661
24262
24263
25253
161
4510
25404
22139
25561
8424
13013
11187
11188
24239
24240
23924
24520
11800
23274
8464
23619
24820
24821
24529
15861
15862
24516
24517
25562
25563
25564
23530
10268
24237
24238
8882
8883
6436
19847
22265
25051
7111
21585
25199
14211
24118
5280
6489
25566
25567
25565
18566
23930
23931
24085
24585
25568
25569
25414
26018
6517
13301
6051
25242
11221
11222
4944
15699
8460
11293
20664
25940
20972
21562
21563
14559
14560
7048
27
11959
8875
8876
22005
24934
13803
24278
4566
11390
11391
25376
7382
12793
1110
19910
14065
14066
6453
6454
10960
20842
419
21038
21039
6468
24580
25570
4163
8461
8462
11346
11347
14240
21379
12621
12376
96
12190
25259
13899
13900
25571
25572
11621
11622
13075
13076
26114
23069
23070
9162
11319
828
11281
23806
24266
22048
24883
6376
23114
12499
12500
25573
25574

In [401]:
ratings =  df.loc[:, 'ratings']
ids = df.loc[:, 'ids']
descriptions = df2.loc[:, 'description']
desc_ids = df2.loc[:,'id']
new_descriptions = []

In [372]:
df2 = pd.read_csv('age_rating_codes_ds.csv')

In [402]:
for c,  rating in enumerate( ratings ):
    for i,  id in enumerate( desc_ids ):
        if id == rating:
            new_descriptions.append(descriptions[i])

In [406]:
len(new_descriptions)
len(ids)

421

In [407]:
df = pd.DataFrame(list(zip(ids, new_descriptions)), 
               columns =['ids', 'descriptions'])

In [408]:
df = d

       ids       descriptions
0    25494   Fantasy Violence
1    25488           Language
2    25485           Language
3    25457   Intense Violence
4    25428           Language
5    25841   Cartoon Violence
6     6032     Comic Mischief
7    24208     Comic Mischief
8    25528     Blood and Gore
9    25529     Blood and Gore
10   24721   Intense Violence
11   25495   Intense Violence
12    9372   Cartoon Violence
13   23490             Lyrics
14   25530  Alcohol Reference
15   25533     Drug Reference
16   25534  Alcohol Reference
17   25535   Intense Violence
18   25536     Blood and Gore
19   25267   Cartoon Violence
20   25437           Language
21   22565   Intense Violence
22   23950   Intense Violence
23    8367              Blood
24   20787             Lyrics
25   20788   Cartoon Violence
26   23541           Language
27   22609   Fantasy Violence
28   23476   Intense Violence
29   23477              Blood
..     ...                ...
391  12621              Blood
392  12376     Drug Reference
393     96           Language
394  12190   Cartoon Violence
395  25259     Comic Mischief
396  13899           Language
397  13900   Cartoon Violence
398  25571   Intense Violence
399  25572     Blood and Gore
400  11621           Language
401  11622   Cartoon Violence
402  13075   Intense Violence
403  13076     Blood and Gore
404  26114   Intense Violence
405  23069   Fantasy Violence
406  23070  Alcohol Reference
407   9162           Language
408  11319   Cartoon Violence
409    828           Language
410  11281     Blood and Gore
411  23806           Language
412  24266   Cartoon Violence
413  22048           Language
414  24883     Drug Reference
415   6376   Intense Violence
416  23114     Blood and Gore
417  12499   Fantasy Violence
418  12500     Animated Blood
419  25573           Language
420  25574   Cartoon Violence

[421 rows x 2 columns]

In [ ]:
#VV----Inactive Code----VV#
# Creating new primary df, saving it
#df = df.set_index('id')
#df.to_csv("age_rating_codes_ds.csv")
tbo_df = df.loc[:,['age_ratings', 'artworks', 'dlcs', 'expansions', 'franchises', 'game_modes', 'genres',\
          'keywords', 'multiplayer_modes', 'release_dates', 'similar_games', 'tags', 'themes']]
df.to_csv("primary_ds_new.csv")